"""Constants for MQTT Discovery Stream."""
ATTR_COLOR = "color"
ATTR_H = "h"
ATTR_S = "s"
ATTR_X = "x"
ATTR_Y = "y"
ATTR_R = "r"
ATTR_G = "g"
ATTR_B = "b"

CONF_BASE_TOPIC = "base_topic"
CONF_DISCOVERY_TOPIC = "discovery_topic"
CONF_PUBLISH_ATTRIBUTES = "publish_attributes"
CONF_PUBLISH_TIMESTAMPS = "publish_timestamps"
CONF_PUBLISH_DISCOVERY = "publish_discovery"

DOMAIN = "mqtt_discoverystream"
